name: decard
description: "PDF → 근거 포함 암기카드 생성기"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  file_picker: ^8.0.0
  google_fonts: ^6.2.0
  url_launcher: ^6.2.0
  share_plus: ^10.0.0
  path_provider: ^2.1.0
  shared_preferences: ^2.3.0
  uuid: ^4.5.1
  web: ^1.1.0
  dio: ^5.9.1
  flutter_web_auth_2: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
  image_path: "assets/icon/app_icon.png"
  adaptive_icon_background: "#C2E7DA"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#1A1B41"
  color_dark: "#121212"
  android_12:
    color: "#1A1B41"
    color_dark: "#121212"
  web: false

flutter:
  uses-material-design: true
